### ISSUE TITLE
DPI: Support for passing a "userId" to the application in the URI which is reflected back in pe/dpi_diagnostics as i.e. userId

### ISSUE THREAD

**Issue by NiclasLindgren** [RuterNo/adt-doc#119]
For instance

dpi/application/app/index.html#display/1?userId=myspecialId

Reflected in diagnostics from the DPI application

pe/dpi_diagnostics {"eventTimestamp":"2023-04-26T12:14:39.411Z","clientId":"49e6bd79d56ad14478cbd8", "userId":"myspecialid","type":"HEARTBEAT"....

This makes it instant to find which sign is a certain Ruter ID and makes fault tracing much easier.

**Comment by eivindga** [comment]
If this is to be implemented, we must make sure to support:

- SLA-monitoring: the logic must either be modified or limited to ADT 3+ where we introduce new SLA-monitoring concepts. 
- Distribution-channels: it is challenging to change the url's in place today, so we should try to avoid that when introducing new concepts. Ref: https://adt.transhub.io/3.x/screen-configs/#distribution-channels

@aevare do you have any additional concerns or comments here?

**Comment by NiclasLindgren** [comment]
I don't see why it is a concern to add another key into the current JSON data on the diagnostics topic per say.

You are not changing the URL you are adding a parameter, it won't effect the URL in any functional way

**Comment by eivindga** [comment]
@NiclasLindgren I referred to the fact that query parameters are included in the "display"-field in the heartbeat today. This field is also validated on the Ruter-backend. Adding query parameters will cause an SLA-breach in todays solution.

**Comment by aevare** [comment]
I don't see any problems with adding this, we might have to clean the user input.

**Comment by Yngve2** [comment]
This will give several benefits:
- Logical CustomerID (screenPosition or IP as provided when provisioning the monitors) will make troubleshooting easier since the ID directly indicate the actual position of monitor.
- The ID will be more stable over time and reduce the amount of "false" SLA-breach. Today the generated ID will give breach even if all monitors is working perfect during revenue trips if the clientID is changed for some reasons.
- Reduce the consequence when the bus is powered down during the app is writing to the localStorace
- A screen with fail on display will not trigg breach. If we replace it, the generated ID will change and result in breach.

**Comment by eivindga** [comment]
Please keep in mind this change is intended to improve maintenance and stability, not to challenge SLA-requirements. Meaning persistence will still be a requirement even with this change in place if it is specified in the contract. See also the browser requirements for ADT3: https://adt.transhub.io/3.x/browser-requirements/

@aevare Some other questions we need to address: 
- duplication of id's: There will be cases where displays on the same vehicle are configured to be using the same id by mistake. We need to have a strategy for how to handle these instances. 
- command message: should this be addressable using the customized id or just the generated id? Perhaps it might be benefiting to support both?

**Comment by Yngve2** [comment]
If the operator initialize 2x display with same id/name/position by mistake, the operator must take the responsibility. In our setup the position is also used for IP-assignment, so it will result in duplicate IP and will cause trouble that easily will be identified and solved.

@NiclasLindgren Please verify...

**Comment by NiclasLindgren** [comment]
Keeping mind that a web browser is allowed to clear the storage at any point it sees fit, as such a webapplication should be prepared to handle a lost local state.

IndexDB, which you use, is under "temporary" category in Chrome. I.e is allowed to be delete at any point in time,.

Also if you don't want the extra query param to be part of the diagnostics, remove it from the URL and put it in a different JSON  variable in the diagnostics message.

We just want to be able to identify the sign on an ID we can relate to.

You won't get the same ID on multiple sign if the MAC address is used.

**Comment by Yngve2** [comment]
We also have to keep in mind that the SLA-requirements is intended to measure the operators contribution to deliver good quality on ADT and passenger experience.

The ClientID today is handled by Ruter-controlled app and the operator have no way to track or understand why it is changed. This is much outside operators control.

**Comment by aevare** [comment]
We will implement this as `physicalId` passed to the application with querystring.
For example: `http://webserver.local/app/?physicalId=screen1#/display/1`.
This can be anything the operator feels helps them to locate the screen.

The diagnostic payload will look like this (simplified)
```
{
  "clientId": "f72a138ffada1E41ccc8ad",
  ...
  "type": "STATUS",
  "payload": {
    "physicalId": "screen1",
    ...
  }
}

```

**Comment by aevare** [comment]
Support for `physicalId` is now in production.
