### ISSUE TITLE
ADT 2.5 - Nye felter for å kunne oppdage dupliserte meldinger

### ISSUE THREAD

**Issue by blacksab** [RuterNo/adt-doc#13]
Alle meldinger til og fra Ruter bør inneholde felter for å kunne avdekke duplikater hos konsumentene

Forslag er å legge til følgende felter i alle meldinger

Felt | Beskrivelse | Required v2.5 | Required v3.0
-- | -- | -- | --
seqNo | auto-increment | no | yes
traceId | unique id | no | yes
eventTimestamp | ISO 8601. Reflects the UTC time when the information was provided.Examples:2022-05-11T09:23:00+02:002022-05-11T07:23:00.000Z | no | yes

**Comment by eivindga** [comment]
EventTimestamp er dekket av #8 . Det har blitt lovet operatørene allerede, så den tror jeg er uproblematisk.

Men trenger vi alle 3 feltene for å vite om noe er duplikat? Særlig seqNo kan være litt krevende å implementere når man har flere produsenter av meldingene.

**Comment by blacksab** [comment]
seqNo er egentlig ikke så viktig så lenge de klarer å sende en traceId som er unik.

**Comment by blacksab** [comment]
Har avklart med Lars (PO) at vi kan gå i gang med å legge til nye felter i meldinger som angår vårt team.

Lager en MR/PR inn til branchen 2.5

**Comment by eivindga** [comment]
Hva med å si eventTimestamp og traceId i alle meldinger, mens seqNo kun i noen spesifikke hvor det er behov for det?

**Comment by blacksab** [comment]
Ja, høres bra ut.

**Comment by mariusw** [comment]
Er traceId riktig navn på et slikt felt? En traceid benyttes for å kunne trace requests gjennom et system i logg-sammenheng, men det er jo ikke det som er formålet med feltet her. Det burde kanskje heller hete messageId, for det er vel DET det egentlig er?

**Comment by blacksab** [comment]
Enig i at det kunne hete messageId.

Tror vi er litt farget av at vi lenge har hatt lyst på en måte å gjenkjenne en melding (og "trace" denne) internt hos oss.

Tar dette opp i teamet :)

**Comment by blacksab** [comment]
Vi bruker traceId på feltet.

Dette fordi det største behovet vi egentlig skal dekke er nettopp intern tracing. Deduplisering er en heldig bieffekt av hva vi ønsker å innføre.

**Comment by mariusw** [comment]
Ah, så det er flere behov dere har ønsket å dekke. Jeg forsto initiativet som et dedupliserings-initiativ. Hvis det er tracing som er hovedmålet så er jeg enig.

**Comment by blacksab** [comment]
Felter lagt til, lukker saken.
