### ISSUE TITLE
ADT 3.0 - Alle meldinger skal ha traceId

### ISSUE THREAD

**Issue by blacksab** [RuterNo/adt-doc#15]
Standardiser alle meldinger til å inneholde traceId.

Dette feltet er etterspurt internt slik at:
* det lettere kan feilsøkes. 
* duplikater lettere kan identifiseres
* enklere å verifisere output

**Comment by eivindga** [comment]
@fredrikbjornoy not all api's have traceId as required. Ex. https://adt.transhub.io/3.x/asyncapi/#operation-publish-pe/doors_individually

Is this by intention, or is this something we can fix?

**Comment by fredrikbjornoy** [comment]
Have updated api's now in MR #113
