### ISSUE TITLE
ADT 2.5 - Fjern topics som tilhører pre-adt2 for sanntid-skjema

### ISSUE THREAD

**Issue by blacksab** [RuterNo/adt-doc#16]
Det har lurt seg inn noen skjema fra pre-adt2. Disse bør fjernes fra alle versjoner

./json-schemas/deviation.json
./json-schemas/signon.json
./json-schemas/tsp.json:3

**Comment by eivindga** [comment]
@blacksab is this still pending, or has it been completed?
