### ISSUE TITLE
ADT 3.0  - consider adding api version in key or payload

### ISSUE THREAD

**Issue by eivindga** [RuterNo/adt-doc#25]
We might need to be able to distinguish between different api versions. 

Should we include api version in the key? Eg.: 

```
{operator}/ruter/{vehicleid}/adt3/pe/dpi/journey
```

**Comment by bfjoren** [comment]
Vi på transportoppdrag syns dette er viktig å få med i ADT 3.

Et forslag er å legge versjon inn i et eget nivå som under.
{operator}/ruter/{vehicleid}/adt/v3/pe/dpi/journey

**Comment by eivindga** [comment]
Det er noen ulemper med å legge det i topic key også, først og fremst hvis det ikke er endringer på api'et mellom adt-versjoner.

Alternativet er å versjonere per topic. Dvs.

{operator}/ruter/{vehicleid}/adt/pe/dpi/journey/v7

**Comment by eivindga** [comment]
Eller funksjonsområde:

{operator}/ruter/{vehicleid}/adt/pe/dpi/v3/journey

**Comment by bfjoren** [comment]
Vi syns man skal beholde majorversjon så kan man ved behov versjonere enkelt-topics 

{operator}/ruter/{vehicleid}/adt/v3/pe/dpi/journey/v7

**Comment by fredrikbjornoy** [comment]
ADT blir versjonert som et på følgende format: `{operator}/ruter/{vehicleid}/adt/v3/#` og `ruter/{operator}/{vehicleid}/adt/v3/#`
