### ISSUE TITLE
ADT 3.0 - depreker topic: oi/current_vehicle_journey/details

### ISSUE THREAD

**Issue by eivindga** [RuterNo/adt-doc#33]
Funksjonaliteten dekkes av: 

- pe/dpi/journey

**Comment by blacksab** [comment]
Er det noe vits å deprekere?

Er det ikke bedre å slette?

Det er jo tross alt en flunkende ny major-versjon vi har :)

**Comment by blacksab** [comment]
Eller, legger vi opp til depreker i 3 for removal i 4?

**Comment by eivindga** [comment]
Tenker kanskje vi kan slette direkte i 3?

Det var intensjonen bak oppgaven, men formulerte meg litt dårlig ser jeg.
