### ISSUE TITLE
ADT 3.0 - Standarder for dato og klokkeslett

### ISSUE THREAD

**Issue by fredrikbjornoy** [RuterNo/adt-doc#38]
Standardisere format og presisjonsnivå på dato / klokkeslett for meldinger som sendes mellom operatør og Ruter.

**Comment by eivindga** [comment]
Forslag: https://ijmacd.github.io/rfc3339-iso8601/

unionen av rfc3339 og iso8601

**Comment by eivindga** [comment]
Tilleggs info: 

- eventTimestamp må ha minimum presisjonsnivå på millisekund. 
- eventuelle andre datoer kan ha strengere krav til format (feks rutetider i oslo tid)
